// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab67_VisaCenterDAL;

namespace lab67_VisaCenterDAL.Migrations
{
    [DbContext(typeof(VisaCenterContext))]
    [Migration("20210113232706_Minor_Changes")]
    partial class Minor_Changes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ConsulId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConsulId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nripey1@gmail.com",
                            Name = "Nazar Ripei"
                        },
                        new
                        {
                            Id = 2,
                            Email = "demetrious@gmail.com",
                            Name = "Dima Soroka"
                        });
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Consul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Consuls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "John Johnson"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 3,
                            Name = "Alice Brown"
                        });
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Australia"
                        });
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Experience = 2,
                            Name = "Ruslana Morhun"
                        },
                        new
                        {
                            Id = 2,
                            Experience = 7,
                            Name = "Denys Furman"
                        },
                        new
                        {
                            Id = 3,
                            Experience = 4,
                            Name = "Olha Fasylenko"
                        });
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "In progress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Declined"
                        });
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Case", b =>
                {
                    b.HasOne("lab67_VisaCenterDAL.Entities.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab67_VisaCenterDAL.Entities.Consul", "Consul")
                        .WithMany("Cases")
                        .HasForeignKey("ConsulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab67_VisaCenterDAL.Entities.Manager", "Manager")
                        .WithMany("Cases")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab67_VisaCenterDAL.Entities.Status", "Status")
                        .WithMany("Cases")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Consul");

                    b.Navigation("Manager");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Consul", b =>
                {
                    b.HasOne("lab67_VisaCenterDAL.Entities.Country", "Country")
                        .WithMany("Consuls")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Client", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Consul", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Country", b =>
                {
                    b.Navigation("Consuls");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Manager", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("lab67_VisaCenterDAL.Entities.Status", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
